ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"    

USER $NB_UID

# Install Python 3 packages
RUN conda install --quiet --yes \
    'pims' \
    'trackpy' \
    'voila' \
    'lmfit' \
    'pybroom' \
    'appmode' \
    'moviepy' \
    'openpyxl' \
    'opencv' \
    'rise' \
    'bokeh' \
    'openpyxl' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
    
    RUN pip install git+https://github.com/rheopy/rheofit.git && \
    git clone https://github.com/rheopy/rheofit.git && \
    git clone https://github.com/marcocaggioni/microrheology_water_test.git && \
    cd microrheology_water_test && \
    mkdir data && \
    cd data && \
    wget https://github.com/marcocaggioni/microrheology_water_test/releases/download/1.0/400nm_100dil_water_01umpix_100fps_short.cin && \
    wget https://github.com/marcocaggioni/microrheology_water_test/releases/download/1.0/400nm_water_01umpix_100fps_short.cine && \
    wget https://github.com/marcocaggioni/microrheology_water_test/releases/download/1.0/400nm_100dil_water_01umpix_100fps_short.mp4 && \
    wget https://github.com/marcocaggioni/microrheology_water_test/releases/download/1.0/400nm_water_01umpix_100fps_short.mp4 &&\
    pip install jupyter-contrib-nbextensions &&\
    jupyter contrib nbextension install --user

WORKDIR $HOME
